include: package:pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false # This project was originally written with double quotes

analyzer:
#   exclude:
#     - path/to/excluded/files/**
