name: fengari_lua
description: Web bindings for Lua 5.3, useful for scripting your web applications.
version: 1.1.0
homepage: https://github.com/PixelToast/dart-fengari-lua

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  quiver: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_web_compilers: ^2.16.4
  pedantic: ^1.11.0
  test: ^1.16.5