name: lua_repl
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  fengari_lua:
    path: ../../

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
